apiVersion: apps/v1
kind: Deployment
metadata:
  name: socket-flow
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: socket-flow
  template:
    metadata:
      labels:
        app: socket-flow
    spec:
      containers:
        - name: socket-flow
          image: felipemeriga1/socket-flow-echo-server:latest
          ports:
            - containerPort: 9002
---
apiVersion: v1
kind: Service
metadata:
  name: socket-flow-service
  namespace: default
spec:
  ports:
    - port: 9002
      targetPort: 9002
  selector:
    app: socket-flow
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: socket-flow-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: app.merigafy.com
      http:
        paths:
          - path: /socket-flow
            pathType: Prefix
            backend:
              service:
                name: socket-flow-service
                port:
                  number: 9002