name: Rust CI/CD Pipeline

on:
  push:
    branches:
      - '**'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Install clippy
        run: rustup component add clippy

      - name: Run clippy
        run: cargo clippy -- -D warnings

  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --verbose

      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose

  autobahn:
    name: Autobahn tests
    runs-on: ubuntu-latest
    needs: build_and_test
    strategy:
      matrix:
        rust:
          - stable

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Running Autobahn TestSuite for the server
        run: ./scripts/autobahn-server.sh

      - name: Upload Autobahn server test results to S3
        run: |
          aws s3 sync ./autobahn/server/ s3://socket-flow-autobahn-server/
        if: github.ref == 'refs/heads/main'

#      - name: Running Autobahn TestSuite for the client
#        run: ./scripts/autobahn-client.sh
#
#      - name: Upload Autobahn client test results to S3
#        run: |
#          aws s3 sync ./autobahn/client/ s3://socket-flow-autobahn-client/
#        if: github.ref == 'refs/heads/main'